version: "3.9"

services:
  mongodb-container:
    image: mongo:5.0.2
    expose:
      - '27017'
  app:
    depends_on:
      - mongodb-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'